#!/bin/sh
#
# @name RoboFalcon
#
# @type Standard Plane
# @class Plane
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.3
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1.0
param set-default CA_SV_CS3_TYPE 4

param set-default PS_SIN_CHANNEL 4
param set-default PS_COS_CHANNEL 10

param set-default PS_SIN_SCL 1.0
param set-default PS_SIN_OFF 0.0
param set-default PS_COS_SCL 1.0
param set-default PS_COS_OFF 0.0

param set-default PS_UP_ANG 0.0
param set-default PS_DOWN_ANG 0.0
param set-default PS_ANG_OFF 0.0

